from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('user_login/', views.user_login, name='user_login'),
    path('recruiter_login/', views.recruiter_login, name='recruiter_login'),
    path('user_signup/', views.user_signup, name='user_signup'),
    path('user_home/', views.user_home, name='user_home'),
    path('Logout/', views.Logout, name='Logout'),
    path('recruiter_signup/', views.recruiter_signup, name='recruiter_signup'),
    path('recruiter_home/', views.recruiter_home, name='recruiter_home'),
    path('view_user/', views.view_user, name='view_user'),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('change_status/<int:id>/', views.change_status, name='change_status'),
    path('recruiter_pending/', views.recruiter_pending, name='recruiter_pending'),
    path('recruiter_accepted/', views.recruiter_accepted, name='recruiter_accepted'),
    path('recruiter_rejected/', views.recruiter_rejected, name='recruiter_rejected'),
    path('recruiter_all/', views.recruiter_all, name='recruiter_all'),
    path('delete_recruiter/<int:id>/', views.delete_recruiter, name='delete_recruiter'),
    path('changepasswordadmin/', views.changepasswordadmin, name='changepasswordadmin'),
    path('changepassworduser/', views.changepassworduser, name='changepassworduser'),
    path('changepasswordrecruiter/', views.changepasswordrecruiter, name='changepasswordrecruiter'),
    path('add_job/', views.add_job, name='add_job'),
    path('job_list/', views.job_list, name='job_list'),
    path('edit_jobdetail/<int:id>', views.edit_jobdetail, name='edit_jobdetail'),
    path('change_companylogo/<int:id>', views.change_companylogo, name='change_companylogo'),
    path('latest_job/', views.latest_job, name='latest_job'),
    path('user_latestjob/', views.user_latestjob, name='user_latestjob'),
    path('job_detail/<int:pid>/', views.job_detail, name='job_detail'),
    path('applyforjob/<int:pid>/', views.applyforjob, name='applyforjob'),
    path('applied_candidatelist/', views.applied_candidatelist, name='applied_candidatelist'),
    path('contactus/', views.contactus, name='contactus'),
]